/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xubuquskwfkseafjjxjy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1YnVxdXNrd2Zrc2VhZmpqeGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMjIyNDcsImV4cCI6MjA4OTU5ODI0N30.V-oiHsuV8sWoeU8x_tof5EZ5ey9G4-Bu8yClBiUNA-U"